name: e2e_pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Maven install
      run: mvn install
    - name: Maven Deploy
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/vs-t -Dtoken=5d27adba383eb824fbd9e83142dc1341528f16b1

